#!/usr/bin/env python3
"""
Initial Schema Migration

Creates every table the application uses. The seed data lands in the
migration after this one so the schema stays separate from its contents.

Revision ID: 0001
Revises:

@package KP WP VulnScan
@author Kevin Pirnie <me@kpirnie.com>
@copyright Copyright (c) 2026
"""

# setup the imports
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by alembic
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Apply this migration

    @return None
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('high_water_mark', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_checkpoints')),
    sa.UniqueConstraint('kind', name=op.f('uq_crawl_checkpoints_kind')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('WORDFENCE', 'NVD', 'CVE', 'LOCAL', name='feedsource', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('auth_type', sa.Enum('NONE', 'BEARER', 'HEADER', 'QUERY', name='feedauth', native_enum=False, length=16), nullable=False),
    sa.Column('auth_param', sa.String(length=64), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=64), nullable=True),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds')),
    sa.UniqueConstraint('source', name=op.f('uq_feeds_source')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('version_key', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('author_profile', sa.String(length=512), nullable=True),
    sa.Column('homepage', sa.String(length=1024), nullable=True),
    sa.Column('download_link', sa.String(length=1024), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('requires_wp', sa.String(length=32), nullable=True),
    sa.Column('tested_wp', sa.String(length=32), nullable=True),
    sa.Column('requires_php', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('num_ratings', sa.Integer(), nullable=False),
    sa.Column('active_installs', sa.BigInteger(), nullable=False),
    sa.Column('downloaded', sa.BigInteger(), nullable=False),
    sa.Column('support_threads', sa.Integer(), nullable=False),
    sa.Column('support_threads_resolved', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ABANDONED', 'MISSING', name='pluginstatus', native_enum=False, length=32), nullable=False),
    sa.Column('closed_reason', sa.String(length=255), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('open_issue_count', sa.Integer(), nullable=False),
    sa.Column('critical_issue_count', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.Column('last_scanned_version', sa.String(length=64), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins')),
    sa.UniqueConstraint('slug', name=op.f('uq_plugins_slug')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_plugins_issue_count'), 'plugins', ['issue_count'], unique=False)
    op.create_index(op.f('ix_plugins_last_crawled'), 'plugins', ['last_crawled'], unique=False)
    op.create_index(op.f('ix_plugins_last_updated'), 'plugins', ['last_updated'], unique=False)
    op.create_index('ix_plugins_priority', 'plugins', ['priority_score', 'issue_count'], unique=False)
    op.create_index('ix_plugins_status_installs', 'plugins', ['status', 'active_installs'], unique=False)
    op.create_index(op.f('ix_plugins_version_key'), 'plugins', ['version_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('WORDFENCE', 'NVD', 'CVE', 'LOCAL', name='feedsource', native_enum=False, length=32), nullable=False),
    sa.Column('source_id', sa.String(length=191), nullable=False),
    sa.Column('cve', sa.String(length=32), nullable=True),
    sa.Column('cve_link', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.Integer(), nullable=True),
    sa.Column('cwe_name', sa.String(length=512), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('informational', sa.Boolean(), nullable=False),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('researchers', sa.JSON(), nullable=True),
    sa.Column('copyright_notice', sa.String(length=512), nullable=True),
    sa.Column('copyright_license', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities')),
    sa.UniqueConstraint('source', 'source_id', name='uq_vulnerabilities_source_source_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vulnerabilities_cve'), 'vulnerabilities', ['cve'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cvss_score'), 'vulnerabilities', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cwe_id'), 'vulnerabilities', ['cwe_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_last_seen'), 'vulnerabilities', ['last_seen'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_published_at'), 'vulnerabilities', ['published_at'], unique=False)
    op.create_index('ix_vulnerabilities_severity_published', 'vulnerabilities', ['severity', 'published_at'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_source'), 'vulnerabilities', ['source'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=191), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_log_created_action', 'audit_log', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('plugin_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=191), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('fk_plugin_tags_plugin_id_plugins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_tags')),
    sa.UniqueConstraint('plugin_id', 'tag', name='uq_plugin_tags_plugin_id_tag'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_plugin_tags_tag'), 'plugin_tags', ['tag'], unique=False)
    op.create_table('plugin_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('version_key', sa.String(length=80), nullable=False),
    sa.Column('download_link', sa.String(length=1024), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('fk_plugin_versions_plugin_id_plugins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_versions')),
    sa.UniqueConstraint('plugin_id', 'version', name='uq_plugin_versions_plugin_id_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_plugin_versions_plugin_key', 'plugin_versions', ['plugin_id', 'version_key'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('SCAN', 'CRAWL', 'FEEDS', 'MATCH', 'REPORT', 'SOURCE_SCAN', name='runkind', native_enum=False, length=32), nullable=False),
    sa.Column('trigger', sa.Enum('CRON', 'MANUAL', 'UI', name='runtrigger', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('plugins_seen', sa.Integer(), nullable=False),
    sa.Column('plugins_added', sa.Integer(), nullable=False),
    sa.Column('plugins_updated', sa.Integer(), nullable=False),
    sa.Column('vulnerabilities_seen', sa.Integer(), nullable=False),
    sa.Column('findings_opened', sa.Integer(), nullable=False),
    sa.Column('findings_resolved', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], name=op.f('fk_runs_started_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_runs_kind_started', 'runs', ['kind', 'started_at'], unique=False)
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=191), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user_expires', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('vulnerability_affects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('software_type', sa.Enum('PLUGIN', 'THEME', 'CORE', name='softwaretype', native_enum=False, length=16), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('software_name', sa.String(length=512), nullable=True),
    sa.Column('from_version', sa.String(length=64), nullable=True),
    sa.Column('from_inclusive', sa.Boolean(), nullable=False),
    sa.Column('to_version', sa.String(length=64), nullable=True),
    sa.Column('to_inclusive', sa.Boolean(), nullable=False),
    sa.Column('from_key', sa.String(length=80), nullable=True),
    sa.Column('to_key', sa.String(length=80), nullable=True),
    sa.Column('patched', sa.Boolean(), nullable=False),
    sa.Column('patched_versions', sa.JSON(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_vulnerability_affects_vulnerability_id_vulnerabilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerability_affects')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vulnerability_affects_range', 'vulnerability_affects', ['slug', 'from_key', 'to_key'], unique=False)
    op.create_index('ix_vulnerability_affects_slug_type', 'vulnerability_affects', ['slug', 'software_type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('affect_id', sa.Integer(), nullable=True),
    sa.Column('matched_version', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'IGNORED', 'FALSE_POSITIVE', name='findingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fix_available', sa.Boolean(), nullable=False),
    sa.Column('fixed_in_version', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affect_id'], ['vulnerability_affects.id'], name=op.f('fk_findings_affect_id_vulnerability_affects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_findings_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_run_id'], ['runs.id'], name=op.f('fk_findings_first_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], name=op.f('fk_findings_last_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('fk_findings_plugin_id_plugins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_findings_vulnerability_id_vulnerabilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('plugin_id', 'vulnerability_id', name='uq_findings_plugin_id_vulnerability_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_findings_plugin_status', 'findings', ['plugin_id', 'status'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index('ix_findings_status_severity', 'findings', ['status', 'severity'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'HTML', name='reportformat', native_enum=False, length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_reports_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index('ix_reports_run_format', 'reports', ['run_id', 'format'], unique=False)
    op.create_table('run_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_stages_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_stages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_run_stages_run_stage', 'run_stages', ['run_id', 'stage'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'RETRYING', 'FAILED', 'SKIPPED', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_webhook_deliveries_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_webhook_deliveries_run_status', 'webhook_deliveries', ['run_id', 'status'], unique=False)
    op.create_table('finding_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STATUS_CHANGED', 'ASSIGNED', 'COMMENTED', 'REOPENED', 'AUTO_RESOLVED', name='findingeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_events_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finding_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_events')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_finding_events_finding_created', 'finding_events', ['finding_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Roll this migration back

    Drops every table in reverse dependency order. The indexes go with
    their tables, we do not drop them separately because mariadb refuses
    to drop an index a foreign key still depends on.

    @return None
    """

    op.drop_table("finding_events")
    op.drop_table("webhook_deliveries")
    op.drop_table("run_stages")
    op.drop_table("reports")
    op.drop_table("findings")
    op.drop_table("vulnerability_affects")
    op.drop_table("user_sessions")
    op.drop_table("settings")
    op.drop_table("runs")
    op.drop_table("plugin_versions")
    op.drop_table("plugin_tags")
    op.drop_table("audit_log")
    op.drop_table("vulnerabilities")
    op.drop_table("users")
    op.drop_table("plugins")
    op.drop_table("feeds")
    op.drop_table("crawl_checkpoints")
